name: Export and Create Pull Request

on:
  repository_dispatch:
    types: [update-design-tokens]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # this lets us work in the actual repository 
      - uses: actions/checkout@master
      # if the folder named "tokens" does not exist, create it
      - name: mkdir "tokens" directory
        # change tokens here (and in line 32) if you want to use a differently named folder 
        run: 'mkdir -p tokens'
      # this creates a json file from the stringified json from the request body
      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          # it uses the figma filename that was send as then filename parameter
          name: ${{ github.event.client_payload.filename }}
          # it uses the json string that was send as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          # it uses the directory named "tokens" to store this json file (change this if you changed it above to use a different folder)
          dir: 'tokens'
      # We now create a pull request 
      - name: Create PR 
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ github.event.client_payload.commitMessage || 'Tokens updated' }}
          title: "Design tokens updated"
          body: "Design tokens have been updated via Figma and need to be reviewed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this parameter is optional and defaults to master but I am using main
          BRANCH_NAME: 'main'
