name: Export and Add Design Tokens

on:
  repository_dispatch:
    types: [update-design-tokens]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Design Tokens JSON File
        run: |
          # Parse the payload sent from the dispatch
          PAYLOAD_FILE=$GITHUB_EVENT_PATH
          TOKENS=$(jq -r '.client_payload.tokens' $PAYLOAD_FILE)
          
          # Create a JSON file with the design tokens
          echo "$TOKENS" > design-tokens.json

      - name: Commit and Push Changes
        run: |
          git config --global user.email "qba.meller2204@gmail.com"
          git config --global user.name "Kuba"
          git add design-tokens.json
          git commit -m "Add design tokens JSON file"
          git push
