name: Export and Create Pull Request

on:
  repository_dispatch:
    types: [update-design-tokens]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Export Design Tokens from Figma
        run: |
          # Your script to export design tokens from Figma here

      - name: Create Design Tokens JSON File
        run: |
          # Your script to generate the design tokens JSON file here

      - name: Commit Design Tokens JSON
        run: |
          git config --global user.email "qba.meller2204@gmail.com"
          git config --global user.name "Kuba"
          git add design-tokens.json
          git commit -m "Add design tokens JSON file"

      - name: Create Pull Request
        run: |
          ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
          REPO_NAME=${{ github.repository }}
          GITHUB_API="https://api.github.com/repos/$REPO_NAME/pulls"

          PR_TITLE="Update Design Tokens"
          PR_BODY="This pull request updates the design tokens."

          curl -X POST -H "Authorization: token $ACCESS_TOKEN" \
            -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"design-tokens-branch\",\"base\":\"main\"}" \
            $GITHUB_API

