name: Export and Add Design Tokens

on:
  repository_dispatch:
    types: [update-design-tokens]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Export Design Tokens from Figma
        run: |
          # Your script to export design tokens from Figma here

      - name: Add Design Tokens to Repository
        run: |
          git config --global user.email "qba.meller2204@gmail.com"
          git config --global user.name "Kuba"
          git add .
          git commit -m "Update design tokens"
          git push
